package org.studyeasy;

public class App {

	public static void main(String[] args) {
		int x = 0, y = 5;
		
		try {
			x = (y = 10*10)/0;
			System.out.println("The statement will not get executed");
		} 
		
		catch(ArithmeticException e) {
			System.out.println("Arithmetic Exception occurred");
		}
		
		catch (Exception e) {
			e.printStackTrace();
			System.out.println("Inside exception block");
		}
		
		
		System.out.println("*****************************");
		System.out.println(y);

	}

}
