package org.studyeasy;

import java.io.FileNotFoundException;


public class App {

	public static void main(String[] args) {
		try {
			someMethod();
		} catch (FileNotFoundException e) {
			System.out.println("Catch block of main method (FileNotFoundException)");
		} catch (Exception e) {
			System.out.println("Catch block of Exception in main");
		}
	}

	public stati2 void someMethod() throws Exception, FileNotFoundException {
		int x = 1;
		
		switch(x) {
			case 1 :
				throw new FileNotFoundException();
			case 2 :
				throw new Exception();
		}
	}
	
}
